### ISSUE TITLE
Security: Consider alternatives to node-wget

### ISSUE THREAD

**Issue by gamebox** [Fepelus/pony-language-server#1]
node-wget relies on a very old version of `request` that has 11 vulnerabilities, including two major ones.  May or may not be related, but running the extension on Ubuntu 18.04 with latest VSCode almost brought down my machine.

Let's consider using wget-improved, which seems to be actively maintained, unlike `node-wget`

**Comment by Fepelus** [comment]
Quite right! For such a simple usage there is no need to go beyond the standard library, to be honest.

https://github.com/Fepelus/pony-language-server/commit/4203331ec089f4d581a1b716451eb5e742e18c96
